### ISSUE TITLE
Completar metodo para el registro de clases al iniciar sesion

### ISSUE THREAD

**Issue by lizbh26** [ashley-lizbeth/Soma#13]
**Como** usuario,
**quiero** guardar la información que obtengo de Google Classroom al iniciar sesión,
**para** que la aplicación pueda guardar dicha información en su base de datos local y pueda utilizarla para mostrar la pantalla de inicio/home.

**Comment by airvzxf** [comment]
Se llevaron a cabo los cambios en los siguientes commits: https://github.com/ashley-lizbeth/Soma/compare/d8ab837b69ce3ef30abbbf0446197c360b34092c...d61c57b157dd2a46cf552e293a1e4b5ba8c7a131
