### ISSUE TITLE
Cambiar el sistema de NextJS a Express

### ISSUE THREAD

**Issue by lizbh26** [ashley-lizbeth/Soma#15]
**Como** desarrollador y arquitecto,
**quiero** cambiar el sistema a Expess,
**porque** es mas eficiente y gasta menos recursos.

**Comment by airvzxf** [comment]
Se realizó el cambio en el commit: https://github.com/ashley-lizbeth/Soma/commit/9294a547ca5c4e710cc67f35ebbb768dc0cce04f
