### ISSUE TITLE
I can't install it.

### ISSUE THREAD

**Issue by airvzxf** [ashley-lizbeth/Soma#2]
I tried to install your system, but I got an error regarding `turbo`. Could you provide guidance about what I need to install? I am using Arch Linux.

```txt
sh: line 1: turbo: command not found 
npm ERR! code 127
npm ERR! path /home/wolf/workspace/projects/Soma
npm ERR! command failed
npm ERR! command sh -c npm run install:expo && npm run db:generate

npm ERR! A complete log of this run can be found in: /home/wolf/.npm/_logs/2023-12-09T16_25_03_562Z-debug-0.log
```

I attached the log file: [2023-12-09T16_25_03_562Z-debug-0.log](https://github.com/ashley-lizbeth/Soma/files/13624948/2023-12-09T16_25_03_562Z-debug-0.log)

**Comment by lizbh26** [comment]
Packages are now updated and instructions in README have been changed to reflect those changes
