### ISSUE TITLE
Spike: Diseñar el proceso y la logica para actualizar la base de datos local

### ISSUE THREAD

**Issue by lizbh26** [ashley-lizbeth/Soma#24]
**Como** desarrollador
**quiero** saber que proceso debe de seguir la app al actualizar datos
**para** poder trabajar eficientemente y sin recurrir a prueba y error

**Comment by lizbh26** [comment]
Este es el flujo a implementar:


![Image](https://github.com/ashley-lizbeth/Soma/assets/124213952/9eb0af1f-e336-42d8-9777-e0e03cce2886)

**Comment by airvzxf** [comment]
Podríamos revisar esto en la próxima sesión. Tengo algunas dudas y presiento que este diagrama se puede extender un poco mejor.

**Comment by airvzxf** [comment]
Este diagrama se podría expandir en los actores que interactúan con la secuencia. También agregar nombre a los actores. Por último, se podría crear una descripción de los tipos de grupos.

![Ejemplo-UML-DiagramaSecuencia](https://github.com/ashley-lizbeth/Soma/assets/831380/1cac061a-e4e7-4fa9-bc7f-bf2e6edc822d)
