### ISSUE TITLE
Spike: Crear cuenta de prueba para Google Classroom

### ISSUE THREAD

**Issue by lizbh26** [ashley-lizbeth/Soma#6]
**Como** desarrollador y tester,
**quiero** un usuario de Google Classroom,
**para** poder probar rápidamente los diferentes escenarios sin necesidad de usar mi cuenta.

**Como** DevOps,
**quiero** tener diferentes usuarios de Google Classroom,
**para** ejecutar las pruebas en el pipeline y realizar sin inconvenientes las construcciones y liberaciones de la aplicación.

**Comment by lizbh26** [comment]
Las credenciales estan en nuestro grupo de Slack.

**Comment by airvzxf** [comment]
Se crearon 3 cuentas más, una de profesor y otras dos de estudiantes.

Además, se ligaron al maestro y alumnos en la cuenta de Google Classroom de [soma.classroom.dev@gmail.com](mailto:soma.classroom.dev@gmail.com), dentro de la clase [Soma Classroom as Teacher](https://classroom.google.com/u/1/c/NjUwMzkwMTQ3MjE3).
