### ISSUE TITLE
Agregar pipeline de seguridad al hacer un commit / merge

### ISSUE THREAD

**Issue by lizbh26** [ashley-lizbeth/Soma#8]
**Como** QA (quality assurance),
**quiero** agregar una tubería de revisión de seguridad,
**para** verificar que nuestro proyecto se puede liberar con el mínimo riesgo de vulnerabilidades de seguridad.

**Comment by airvzxf** [comment]
Queda temporalmente bloqueada esta historia, ya que en la investigación encontré que `Snyk security` es uno de los mejores, así que requiero que @ashley-lizbeth me apoye creando una cuenta para el proyecto.

Para más información, consultar la nueva historia: [Crear cuenta de Synk para el escaneo de seguridad #38](https://github.com/ashley-lizbeth/Soma/issues/38).

**Comment by airvzxf** [comment]
Se agregó en el Pull Request: https://github.com/ashley-lizbeth/Soma/pull/45
