### ISSUE TITLE
Agregar un pipeline para escaneo y formateo del codigo

### ISSUE THREAD

**Issue by lizbh26** [ashley-lizbeth/Soma#9]
**Como** QA (quality assurance),
**quiero** una tubería para escanear y formatear el código fuente,
**para** asegurarme que no tiene posibles bugs, que está bien programado y que no contenga posibles errores de seguridad.

**Comment by lizbh26** [comment]
ESlint no escanea apps/expo porque el flujo de acceso a la base de datos aun no esta terminado, por lo que detecta muchos errores. Queda pendiente.

**Comment by airvzxf** [comment]
Se realizó el pipeline, pero necesita terminarse primero el módulo de App/Expo para que no arroje errores. Se creó historia al respecto: Habilitar App/Expo al pipeline de escaneo #29.
